# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Calc_UI.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_SuperCalc(object):
    def setupUi(self, SuperCalc):
        if not SuperCalc.objectName():
            SuperCalc.setObjectName(u"SuperCalc")
        SuperCalc.resize(281, 295)
        SuperCalc.setMinimumSize(QSize(281, 295))
        SuperCalc.setMaximumSize(QSize(281, 295))
        self.display = QLabel(SuperCalc)
        self.display.setObjectName(u"display")
        self.display.setGeometry(QRect(20, 20, 241, 41))
        font = QFont()
        font.setPointSize(12)
        self.display.setFont(font)
        self.display.setFrameShape(QFrame.Box)
        self.display.setFrameShadow(QFrame.Plain)
        self.display.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.display.setIndent(10)
        self.button_seven = QPushButton(SuperCalc)
        self.buttonGroup_num = QButtonGroup(SuperCalc)
        self.buttonGroup_num.setObjectName(u"buttonGroup_num")
        self.buttonGroup_num.addButton(self.button_seven)
        self.button_seven.setObjectName(u"button_seven")
        self.button_seven.setGeometry(QRect(20, 80, 41, 41))
        font1 = QFont()
        font1.setPointSize(20)
        self.button_seven.setFont(font1)
        self.button_eight = QPushButton(SuperCalc)
        self.buttonGroup_num.addButton(self.button_eight)
        self.button_eight.setObjectName(u"button_eight")
        self.button_eight.setGeometry(QRect(70, 80, 41, 41))
        self.button_eight.setFont(font1)
        self.button_nine = QPushButton(SuperCalc)
        self.buttonGroup_num.addButton(self.button_nine)
        self.button_nine.setObjectName(u"button_nine")
        self.button_nine.setGeometry(QRect(120, 80, 41, 41))
        self.button_nine.setFont(font1)
        self.pushButton_4 = QPushButton(SuperCalc)
        self.buttonGroup_oper = QButtonGroup(SuperCalc)
        self.buttonGroup_oper.setObjectName(u"buttonGroup_oper")
        self.buttonGroup_oper.addButton(self.pushButton_4)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(170, 80, 41, 41))
        self.pushButton_4.setFont(font1)
        self.button_six = QPushButton(SuperCalc)
        self.buttonGroup_num.addButton(self.button_six)
        self.button_six.setObjectName(u"button_six")
        self.button_six.setGeometry(QRect(120, 130, 41, 41))
        self.button_six.setFont(font1)
        self.pushButton_6 = QPushButton(SuperCalc)
        self.buttonGroup_oper.addButton(self.pushButton_6)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(170, 130, 41, 41))
        self.pushButton_6.setFont(font1)
        self.button_five = QPushButton(SuperCalc)
        self.buttonGroup_num.addButton(self.button_five)
        self.button_five.setObjectName(u"button_five")
        self.button_five.setGeometry(QRect(70, 130, 41, 41))
        self.button_five.setFont(font1)
        self.button_four = QPushButton(SuperCalc)
        self.buttonGroup_num.addButton(self.button_four)
        self.button_four.setObjectName(u"button_four")
        self.button_four.setGeometry(QRect(20, 130, 41, 41))
        self.button_four.setFont(font1)
        self.bitton_three = QPushButton(SuperCalc)
        self.buttonGroup_num.addButton(self.bitton_three)
        self.bitton_three.setObjectName(u"bitton_three")
        self.bitton_three.setGeometry(QRect(120, 180, 41, 41))
        self.bitton_three.setFont(font1)
        self.pushButton_10 = QPushButton(SuperCalc)
        self.buttonGroup_oper.addButton(self.pushButton_10)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(170, 180, 41, 41))
        self.pushButton_10.setFont(font1)
        self.button_two = QPushButton(SuperCalc)
        self.buttonGroup_num.addButton(self.button_two)
        self.button_two.setObjectName(u"button_two")
        self.button_two.setGeometry(QRect(70, 180, 41, 41))
        self.button_two.setFont(font1)
        self.button_one = QPushButton(SuperCalc)
        self.buttonGroup_num.addButton(self.button_one)
        self.button_one.setObjectName(u"button_one")
        self.button_one.setGeometry(QRect(20, 180, 41, 41))
        self.button_one.setFont(font1)
        self.pushButton_14 = QPushButton(SuperCalc)
        self.buttonGroup_oper.addButton(self.pushButton_14)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(170, 230, 41, 41))
        self.pushButton_14.setFont(font1)
        self.pushButton_15 = QPushButton(SuperCalc)
        self.buttonGroup_num.addButton(self.pushButton_15)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setGeometry(QRect(20, 230, 91, 41))
        self.pushButton_15.setFont(font1)
        self.pushButton_point = QPushButton(SuperCalc)
        self.pushButton_point.setObjectName(u"pushButton_point")
        self.pushButton_point.setGeometry(QRect(120, 230, 41, 41))
        self.pushButton_point.setFont(font1)
        self.equal = QPushButton(SuperCalc)
        self.equal.setObjectName(u"equal")
        self.equal.setGeometry(QRect(220, 180, 41, 91))
        self.equal.setFont(font1)
        self.button_clear = QPushButton(SuperCalc)
        self.button_clear.setObjectName(u"button_clear")
        self.button_clear.setGeometry(QRect(220, 80, 41, 91))
        self.button_clear.setFont(font1)

        self.retranslateUi(SuperCalc)

        QMetaObject.connectSlotsByName(SuperCalc)
    # setupUi

    def retranslateUi(self, SuperCalc):
        SuperCalc.setWindowTitle(QCoreApplication.translate("SuperCalc", u"Form", None))
        self.display.setText(QCoreApplication.translate("SuperCalc", u"0.0", None))
        self.button_seven.setText(QCoreApplication.translate("SuperCalc", u"7", None))
        self.button_eight.setText(QCoreApplication.translate("SuperCalc", u"8", None))
        self.button_nine.setText(QCoreApplication.translate("SuperCalc", u"9", None))
        self.pushButton_4.setText(QCoreApplication.translate("SuperCalc", u"+", None))
        self.button_six.setText(QCoreApplication.translate("SuperCalc", u"6", None))
        self.pushButton_6.setText(QCoreApplication.translate("SuperCalc", u"-", None))
        self.button_five.setText(QCoreApplication.translate("SuperCalc", u"5", None))
        self.button_four.setText(QCoreApplication.translate("SuperCalc", u"4", None))
        self.bitton_three.setText(QCoreApplication.translate("SuperCalc", u"3", None))
        self.pushButton_10.setText(QCoreApplication.translate("SuperCalc", u"*", None))
        self.button_two.setText(QCoreApplication.translate("SuperCalc", u"2", None))
        self.button_one.setText(QCoreApplication.translate("SuperCalc", u"1", None))
        self.pushButton_14.setText(QCoreApplication.translate("SuperCalc", u"/", None))
        self.pushButton_15.setText(QCoreApplication.translate("SuperCalc", u"0", None))
        self.pushButton_point.setText(QCoreApplication.translate("SuperCalc", u".", None))
        self.equal.setText(QCoreApplication.translate("SuperCalc", u"=", None))
        self.button_clear.setText(QCoreApplication.translate("SuperCalc", u"C", None))
    # retranslateUi

