# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Calc_UI.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(281, 295)
        Form.setMinimumSize(QSize(281, 295))
        Form.setMaximumSize(QSize(281, 295))
        self.display = QLabel(Form)
        self.display.setObjectName(u"display")
        self.display.setGeometry(QRect(20, 20, 241, 41))
        font = QFont()
        font.setPointSize(18)
        self.display.setFont(font)
        self.display.setFrameShape(QFrame.Box)
        self.display.setFrameShadow(QFrame.Plain)
        self.display.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.display.setIndent(10)
        self.button_seven = QPushButton(Form)
        self.buttonGroup = QButtonGroup(Form)
        self.buttonGroup.setObjectName(u"buttonGroup")
        self.buttonGroup.addButton(self.button_seven)
        self.button_seven.setObjectName(u"button_seven")
        self.button_seven.setGeometry(QRect(20, 80, 41, 41))
        font1 = QFont()
        font1.setPointSize(20)
        self.button_seven.setFont(font1)
        self.button_eight = QPushButton(Form)
        self.buttonGroup.addButton(self.button_eight)
        self.button_eight.setObjectName(u"button_eight")
        self.button_eight.setGeometry(QRect(70, 80, 41, 41))
        self.button_eight.setFont(font1)
        self.button_nine = QPushButton(Form)
        self.buttonGroup.addButton(self.button_nine)
        self.button_nine.setObjectName(u"button_nine")
        self.button_nine.setGeometry(QRect(120, 80, 41, 41))
        self.button_nine.setFont(font1)
        self.pushButton_4 = QPushButton(Form)
        self.buttonGroup.addButton(self.pushButton_4)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(170, 80, 41, 41))
        self.pushButton_4.setFont(font1)
        self.button_six = QPushButton(Form)
        self.buttonGroup.addButton(self.button_six)
        self.button_six.setObjectName(u"button_six")
        self.button_six.setGeometry(QRect(120, 130, 41, 41))
        self.button_six.setFont(font1)
        self.pushButton_6 = QPushButton(Form)
        self.buttonGroup.addButton(self.pushButton_6)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(170, 130, 41, 41))
        self.pushButton_6.setFont(font1)
        self.button_five = QPushButton(Form)
        self.buttonGroup.addButton(self.button_five)
        self.button_five.setObjectName(u"button_five")
        self.button_five.setGeometry(QRect(70, 130, 41, 41))
        self.button_five.setFont(font1)
        self.button_four = QPushButton(Form)
        self.buttonGroup.addButton(self.button_four)
        self.button_four.setObjectName(u"button_four")
        self.button_four.setGeometry(QRect(20, 130, 41, 41))
        self.button_four.setFont(font1)
        self.bitton_three = QPushButton(Form)
        self.buttonGroup.addButton(self.bitton_three)
        self.bitton_three.setObjectName(u"bitton_three")
        self.bitton_three.setGeometry(QRect(120, 180, 41, 41))
        self.bitton_three.setFont(font1)
        self.pushButton_10 = QPushButton(Form)
        self.buttonGroup.addButton(self.pushButton_10)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(170, 180, 41, 41))
        self.pushButton_10.setFont(font1)
        self.button_two = QPushButton(Form)
        self.buttonGroup.addButton(self.button_two)
        self.button_two.setObjectName(u"button_two")
        self.button_two.setGeometry(QRect(70, 180, 41, 41))
        self.button_two.setFont(font1)
        self.button_one = QPushButton(Form)
        self.buttonGroup.addButton(self.button_one)
        self.button_one.setObjectName(u"button_one")
        self.button_one.setGeometry(QRect(20, 180, 41, 41))
        self.button_one.setFont(font1)
        self.pushButton_14 = QPushButton(Form)
        self.buttonGroup.addButton(self.pushButton_14)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(170, 230, 41, 41))
        self.pushButton_14.setFont(font1)
        self.pushButton_15 = QPushButton(Form)
        self.buttonGroup.addButton(self.pushButton_15)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setGeometry(QRect(20, 230, 91, 41))
        self.pushButton_15.setFont(font1)
        self.pushButton_16 = QPushButton(Form)
        self.buttonGroup.addButton(self.pushButton_16)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.pushButton_16.setGeometry(QRect(120, 230, 41, 41))
        self.pushButton_16.setFont(font1)
        self.pushButton_11 = QPushButton(Form)
        self.buttonGroup.addButton(self.pushButton_11)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(220, 180, 41, 91))
        self.pushButton_11.setFont(font1)
        self.button_clear = QPushButton(Form)
        self.buttonGroup.addButton(self.button_clear)
        self.button_clear.setObjectName(u"button_clear")
        self.button_clear.setGeometry(QRect(220, 80, 41, 41))
        self.button_clear.setFont(font1)
        self.pushButton_7 = QPushButton(Form)
        self.buttonGroup.addButton(self.pushButton_7)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(220, 130, 41, 41))
        self.pushButton_7.setFont(font1)

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.display.setText(QCoreApplication.translate("Form", u"123456789.0", None))
        self.button_seven.setText(QCoreApplication.translate("Form", u"7", None))
        self.button_eight.setText(QCoreApplication.translate("Form", u"8", None))
        self.button_nine.setText(QCoreApplication.translate("Form", u"9", None))
        self.pushButton_4.setText(QCoreApplication.translate("Form", u"+", None))
        self.button_six.setText(QCoreApplication.translate("Form", u"6", None))
        self.pushButton_6.setText(QCoreApplication.translate("Form", u"\u2212", None))
        self.button_five.setText(QCoreApplication.translate("Form", u"5", None))
        self.button_four.setText(QCoreApplication.translate("Form", u"4", None))
        self.bitton_three.setText(QCoreApplication.translate("Form", u"3", None))
        self.pushButton_10.setText(QCoreApplication.translate("Form", u"*", None))
        self.button_two.setText(QCoreApplication.translate("Form", u"2", None))
        self.button_one.setText(QCoreApplication.translate("Form", u"1", None))
        self.pushButton_14.setText(QCoreApplication.translate("Form", u"/", None))
        self.pushButton_15.setText(QCoreApplication.translate("Form", u"0", None))
        self.pushButton_16.setText(QCoreApplication.translate("Form", u".", None))
        self.pushButton_11.setText(QCoreApplication.translate("Form", u"=", None))
        self.button_clear.setText(QCoreApplication.translate("Form", u"C", None))
        self.pushButton_7.setText(QCoreApplication.translate("Form", u"\u221a", None))
    # retranslateUi

